// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* terminator */
			nil,      /* empty */
			shift(5), /* import */
			nil,      /* as */
			nil,      /* . */
			nil,      /* identifier */
			nil,      /* floatLit */
			nil,      /* intLit */
			nil,      /* runeLit */
			nil,      /* stringLit */
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          /* INVALID */
			accept(true), /* $ */
			nil,          /* terminator */
			nil,          /* empty */
			nil,          /* import */
			nil,          /* as */
			nil,          /* . */
			nil,          /* identifier */
			nil,          /* floatLit */
			nil,          /* intLit */
			nil,          /* runeLit */
			nil,          /* stringLit */
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(4), /* $, reduce: RepeatTerminator */
			shift(6),  /* terminator */
			nil,       /* empty */
			nil,       /* import */
			nil,       /* as */
			nil,       /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(5), /* $, reduce: Statement */
			reduce(5), /* terminator, reduce: Statement */
			nil,       /* empty */
			nil,       /* import */
			nil,       /* as */
			nil,       /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(6), /* $, reduce: Statement */
			reduce(6), /* terminator, reduce: Statement */
			nil,       /* empty */
			nil,       /* import */
			nil,       /* as */
			nil,       /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* terminator */
			nil,       /* empty */
			nil,       /* import */
			nil,       /* as */
			nil,       /* . */
			shift(10), /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(4), /* $, reduce: RepeatTerminator */
			shift(11), /* terminator */
			nil,       /* empty */
			reduce(4), /* import, reduce: RepeatTerminator */
			nil,       /* as */
			nil,       /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(2), /* $, reduce: StatementList */
			nil,       /* terminator */
			nil,       /* empty */
			nil,       /* import */
			nil,       /* as */
			nil,       /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(8), /* $, reduce: ImportNormalDeclaration */
			reduce(8), /* terminator, reduce: ImportNormalDeclaration */
			nil,       /* empty */
			nil,       /* import */
			shift(13), /* as */
			nil,       /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(9), /* $, reduce: Namespace */
			reduce(9), /* terminator, reduce: Namespace */
			nil,       /* empty */
			nil,       /* import */
			reduce(9), /* as, reduce: Namespace */
			shift(14), /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(11), /* $, reduce: Identifier */
			reduce(11), /* terminator, reduce: Identifier */
			nil,        /* empty */
			nil,        /* import */
			reduce(11), /* as, reduce: Identifier */
			reduce(11), /* ., reduce: Identifier */
			nil,        /* identifier */
			nil,        /* floatLit */
			nil,        /* intLit */
			nil,        /* runeLit */
			nil,        /* stringLit */
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(4), /* $, reduce: RepeatTerminator */
			shift(11), /* terminator */
			nil,       /* empty */
			reduce(4), /* import, reduce: RepeatTerminator */
			nil,       /* as */
			nil,       /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(3), /* $, reduce: RepeatTerminator */
			nil,       /* terminator */
			nil,       /* empty */
			shift(5),  /* import */
			nil,       /* as */
			nil,       /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* terminator */
			nil,       /* empty */
			nil,       /* import */
			nil,       /* as */
			nil,       /* . */
			shift(18), /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* terminator */
			nil,       /* empty */
			nil,       /* import */
			nil,       /* as */
			nil,       /* . */
			shift(10), /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(3), /* $, reduce: RepeatTerminator */
			nil,       /* terminator */
			nil,       /* empty */
			reduce(3), /* import, reduce: RepeatTerminator */
			nil,       /* as */
			nil,       /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(1), /* $, reduce: StatementList */
			nil,       /* terminator */
			nil,       /* empty */
			nil,       /* import */
			nil,       /* as */
			nil,       /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(7), /* $, reduce: ImportAsDeclaration */
			reduce(7), /* terminator, reduce: ImportAsDeclaration */
			nil,       /* empty */
			nil,       /* import */
			nil,       /* as */
			nil,       /* . */
			nil,       /* identifier */
			nil,       /* floatLit */
			nil,       /* intLit */
			nil,       /* runeLit */
			nil,       /* stringLit */
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(11), /* $, reduce: Identifier */
			reduce(11), /* terminator, reduce: Identifier */
			nil,        /* empty */
			nil,        /* import */
			nil,        /* as */
			nil,        /* . */
			nil,        /* identifier */
			nil,        /* floatLit */
			nil,        /* intLit */
			nil,        /* runeLit */
			nil,        /* stringLit */
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(10), /* $, reduce: Namespace */
			reduce(10), /* terminator, reduce: Namespace */
			nil,        /* empty */
			nil,        /* import */
			reduce(10), /* as, reduce: Namespace */
			nil,        /* . */
			nil,        /* identifier */
			nil,        /* floatLit */
			nil,        /* intLit */
			nil,        /* runeLit */
			nil,        /* stringLit */
		},
	},
}
