// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 8

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // StatementList
		-1, // RepeatTerminator
		2,  // Statement
		3,  // ImportAsDeclaration
		4,  // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S1
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S2
		-1, // S'
		-1, // StatementList
		7,  // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S3
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S4
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S5
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		8,  // Namespace
		9,  // Identifier
	},
	gotoRow{ // S6
		-1, // S'
		-1, // StatementList
		12, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S7
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S8
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S9
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S10
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S11
		-1, // S'
		-1, // StatementList
		15, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S12
		-1, // S'
		16, // StatementList
		-1, // RepeatTerminator
		2,  // Statement
		3,  // ImportAsDeclaration
		4,  // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S13
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		17, // Identifier
	},
	gotoRow{ // S14
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		19, // Namespace
		9,  // Identifier
	},
	gotoRow{ // S15
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S16
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S17
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S18
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
	gotoRow{ // S19
		-1, // S'
		-1, // StatementList
		-1, // RepeatTerminator
		-1, // Statement
		-1, // ImportAsDeclaration
		-1, // ImportNormalDeclaration
		-1, // Namespace
		-1, // Identifier
	},
}
