// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/Soontao/pdi-util/ast/token"
)

const (
	NoState    = -1
	NumStates  = 51
	NumSymbols = 58
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: ';'
1: '\n'
2: ';'
3: '\n'
4: '.'
5: '.'
6: '''
7: '\'
8: '''
9: 'i'
10: 'm'
11: 'p'
12: 'o'
13: 'r'
14: 't'
15: 'a'
16: 's'
17: '.'
18: '/'
19: '/'
20: '\n'
21: '/'
22: '*'
23: '*'
24: '*'
25: '/'
26: '_'
27: '0'
28: '0'
29: 'x'
30: 'X'
31: 'e'
32: 'E'
33: '+'
34: '-'
35: '`'
36: '`'
37: '"'
38: '\'
39: '"'
40: '"'
41: '\'
42: 'n'
43: '\'
44: 'r'
45: '\'
46: 't'
47: ' '
48: '\t'
49: '\r'
50: 'a'-'z'
51: 'A'-'Z'
52: '0'-'9'
53: '0'-'7'
54: 'a'-'f'
55: 'A'-'F'
56: '1'-'9'
57: .
*/
