// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 2
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 34: // ['"','"']
			return 3
		case r == 39: // [''',''']
			return 4
		case r == 46: // ['.','.']
			return 5
		case r == 47: // ['/','/']
			return 6
		case r == 48: // ['0','0']
			return 7
		case 49 <= r && r <= 57: // ['1','9']
			return 8
		case r == 59: // [';',';']
			return 9
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case r == 96: // ['`','`']
			return 12
		case r == 97: // ['a','a']
			return 13
		case 98 <= r && r <= 104: // ['b','h']
			return 10
		case r == 105: // ['i','i']
			return 14
		case 106 <= r && r <= 122: // ['j','z']
			return 10
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 15
		case r == 92: // ['\','\']
			return 16
		default:
			return 3
		}
	},
	// S4
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 17
		case r == 92: // ['\','\']
			return 18
		default:
			return 19
		}
	},
	// S5
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 20
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 21
		case r == 47: // ['/','/']
			return 22
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 55: // ['0','7']
			return 24
		case 56 <= r && r <= 57: // ['8','9']
			return 25
		case r == 69: // ['E','E']
			return 26
		case r == 88: // ['X','X']
			return 27
		case r == 101: // ['e','e']
			return 26
		case r == 120: // ['x','x']
			return 27
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 57: // ['0','9']
			return 8
		case r == 69: // ['E','E']
			return 26
		case r == 101: // ['e','e']
			return 26
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 2
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 10
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 10
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 96: // ['`','`']
			return 29
		default:
			return 12
		}
	},
	// S13
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 114: // ['a','r']
			return 10
		case r == 115: // ['s','s']
			return 30
		case 116 <= r && r <= 122: // ['t','z']
			return 10
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 108: // ['a','l']
			return 10
		case r == 109: // ['m','m']
			return 31
		case 110 <= r && r <= 122: // ['n','z']
			return 10
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 3
		case r == 110: // ['n','n']
			return 32
		case r == 114: // ['r','r']
			return 32
		case r == 116: // ['t','t']
			return 32
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 17
		default:
			return 19
		}
	},
	// S19
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 17
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 20
		case r == 69: // ['E','E']
			return 33
		case r == 101: // ['e','e']
			return 33
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 34
		default:
			return 21
		}
	},
	// S22
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 35
		default:
			return 22
		}
	},
	// S23
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 36
		case r == 69: // ['E','E']
			return 37
		case r == 101: // ['e','e']
			return 37
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 55: // ['0','7']
			return 24
		case 56 <= r && r <= 57: // ['8','9']
			return 25
		case r == 69: // ['E','E']
			return 26
		case r == 101: // ['e','e']
			return 26
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 57: // ['0','9']
			return 25
		case r == 69: // ['E','E']
			return 26
		case r == 101: // ['e','e']
			return 26
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 38
		case r == 45: // ['-','-']
			return 38
		case 48 <= r && r <= 57: // ['0','9']
			return 39
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 70: // ['A','F']
			return 41
		case 97 <= r && r <= 102: // ['a','f']
			return 41
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 10
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 10
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 111: // ['a','o']
			return 10
		case r == 112: // ['p','p']
			return 42
		case 113 <= r && r <= 122: // ['q','z']
			return 10
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 15
		case r == 92: // ['\','\']
			return 16
		default:
			return 3
		}
	},
	// S33
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 43
		case r == 45: // ['-','-']
			return 43
		case 48 <= r && r <= 57: // ['0','9']
			return 44
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 34
		case r == 47: // ['/','/']
			return 45
		default:
			return 21
		}
	},
	// S35
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 36
		case r == 69: // ['E','E']
			return 37
		case r == 101: // ['e','e']
			return 37
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 46
		case r == 45: // ['-','-']
			return 46
		case 48 <= r && r <= 57: // ['0','9']
			return 47
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 39
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 39
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 70: // ['A','F']
			return 41
		case 97 <= r && r <= 102: // ['a','f']
			return 41
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 70: // ['A','F']
			return 41
		case 97 <= r && r <= 102: // ['a','f']
			return 41
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 110: // ['a','n']
			return 10
		case r == 111: // ['o','o']
			return 48
		case 112 <= r && r <= 122: // ['p','z']
			return 10
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 44
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 44
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 47
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 47
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 113: // ['a','q']
			return 10
		case r == 114: // ['r','r']
			return 49
		case 115 <= r && r <= 122: // ['s','z']
			return 10
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 115: // ['a','s']
			return 10
		case r == 116: // ['t','t']
			return 50
		case 117 <= r && r <= 122: // ['u','z']
			return 10
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 10
		case r == 95: // ['_','_']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 10
		}
		return NoState
	},
}
