// PDI Solution Continuous Deployment Jenkinsfile
// Jenkins must install the 'fileOperations' and 'withCredentials' plugins
// For the 'Deploy' stage, the source & target tenant must have the same 'Release' version

// Recommendation, please use this CD pipeline after first-time deployment
// first-time deploy is not testes by 'pdi-util project' by now

// Recommendation, please import this jenkinsfile as normal 'Pipeline' (instead of Multi Branch Pipeline), 
// so that you could control build/deployment flexible

// This pipeline will assemble a new package in the source tenant and popup a new version (create patch)
// This pipeline will deploy the assembled package to target tenant and activate it after uploading

def cliVersion = "v2.0.17"

// def os = "darwin" // MacOS
// def os = "windows" // windows
def os = "linux" // linux

def cliName = "pdiutil-${cliVersion}-${os}-amd64" // linux, macos
// def cliName = "pdiutil-${cliVersion}-${os}-amd64.exe" // for windows

def utilDownloadURI = "https://github.com/Soontao/pdi-util/releases/download/${cliVersion}/${cliName}.zip"

def utilZipFileName = "pdiutil.zip"

// please use the readable 'Solution Description' instead of the technical 'Solution ID'
// so that pdi-util tool can auto detect the correct solution id after patch solution created
def solution = ""

// source tenant, like my000000.sapbyd.cn
def devTenant = ""

// target tenant, like my000001.sapbyd.cn
def targetTenant = ""

// Jenkins user/password credential ID
def devUserCredentialId = ''

// Jenkins user/password credential ID
def targetUserCredentialId = ''

pipeline {

	agent any

	environment { 

		// for assemble 
		PDI_TENANT_HOST = "${devTenant}"
		// for assemble
		SOLUTION_NAME = "${solution}"
		// for deploy
		TARGET_TENANT = "${targetTenant}"
		// for deploy
		SOURCE_SOLUTION_NAME = "${solution}"

	}

	stages {

		// download pdi tool from CDN
		stage('Setup') {
			steps {
				script {
					fileOperations([
						fileDownloadOperation(targetLocation: '', userName: '', password: '', targetFileName: utilZipFileName, url: utilDownloadURI),
						fileUnZipOperation(filePath: utilZipFileName, targetLocation: '')
					])
				}
			}
		}

		stage('Build') {

			steps {
				lock(devTenant) {
					withCredentials([usernamePassword(credentialsId: devUserCredentialId, passwordVariable: 'PDI_PASSWORD', usernameVariable: 'PDI_USER')]) {
						sh script: "./${cliName} package assemble", label: "Assemble & Download"
						archiveArtifacts artifacts: '*.zip', excludes: utilZipFileName
					}
				}
			}

		}

		stage('Deploy') {

			steps {
				lock(targetTenant) {
					withCredentials([usernamePassword(credentialsId: devUserCredentialId, passwordVariable: 'PDI_PASSWORD', usernameVariable: 'PDI_USER'), usernamePassword(credentialsId: targetUserCredentialId, passwordVariable: 'TARGET_TENANT_PASSWORD', usernameVariable: 'TARGET_TENANT_USER')]) {
						sh script: "./${cliName} solution deploy", label: "Deploy to target tenant"
					}
				}
			}

		}


		stage('Check afte deployment') {

			steps {
				lock(targetTenant) {
					withCredentials([usernamePassword(credentialsId: targetUserCredentialId, passwordVariable: 'PDI_PASSWORD', usernameVariable: 'PDI_USER')]) {
						sh script: "./${cliName} check backend", label: "Target Tenant Backend Check"
					}
				}
			}

		}


		stage('Clean') {

			// clean workspace 
			steps{
				deleteDir()
			}

		}

	}

}
